name = "PlotlyDocumenter"
uuid = "9b90f1cd-2639-4507-8b17-2fbe371ceceb"
authors = ["Alberto Mengali <disberd@gmail.com>"]
version = "0.1.1"

[deps]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
PackageExtensionCompat = "65ce6f38-6b18-4e1d-a461-8949797d7930"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[weakdeps]
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"
PlotlyLight = "ca7969ec-10b3-423e-8d99-40f33abb42bf"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"

[extensions]
PlotlyBaseExt = "PlotlyBase"
PlotlyJSExt = "PlotlyJS"
PlotlyLightExt = "PlotlyLight"

[compat]
HypertextLiteral = "0.9"
PackageExtensionCompat = "1"
Downloads = "1"
julia = "1.8"

[extras]
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"
PlotlyLight = "ca7969ec-10b3-423e-8d99-40f33abb42bf"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "PlotlyBase", "PlotlyLight", "PlotlyJS"]
